// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnAFYsZzG0EiZbp_7aC40UkTfAZPZS5iQ',
    appId: '1:383198260398:web:48177b10c6bbef0dc3513f',
    messagingSenderId: '383198260398',
    projectId: 'chat-app-flutter-bf24d',
    authDomain: 'chat-app-flutter-bf24d.firebaseapp.com',
    storageBucket: 'chat-app-flutter-bf24d.appspot.com',
    measurementId: 'G-61JWS0LF5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZJGSz_D00h2ZcHAgn_FX4n8z8_0MLACo',
    appId: '1:383198260398:android:9adf82450639d596c3513f',
    messagingSenderId: '383198260398',
    projectId: 'chat-app-flutter-bf24d',
    storageBucket: 'chat-app-flutter-bf24d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiAQJP-1J0vKBX8yd6Ck9JMOMbfgOgY5k',
    appId: '1:383198260398:ios:e96c96501787f2c7c3513f',
    messagingSenderId: '383198260398',
    projectId: 'chat-app-flutter-bf24d',
    storageBucket: 'chat-app-flutter-bf24d.appspot.com',
    iosClientId: '383198260398-4v0dt82b3sicup6bca01gs6q45mmnop4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiAQJP-1J0vKBX8yd6Ck9JMOMbfgOgY5k',
    appId: '1:383198260398:ios:e96c96501787f2c7c3513f',
    messagingSenderId: '383198260398',
    projectId: 'chat-app-flutter-bf24d',
    storageBucket: 'chat-app-flutter-bf24d.appspot.com',
    iosClientId: '383198260398-4v0dt82b3sicup6bca01gs6q45mmnop4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );
}
